"""API Schemas - Pydantic models for request/response validation"""

# Public Agent API schemas (CORE 2 #7 — JSON+SSE contract for /api/v1/agent/*)
from .agent import (
    AgentRunMeta,
    AgentRunRequest,
    AgentRunResponse,
    AgentStreamEvent,
    CriticEvent,
    CriticScores,
    DoneEvent,
    ErrorEvent,
    MediaCounts,
    PlannerEvent,
    PlannerInfo,
    RetrieverEvent,
    RetrieverInfo,
    WriterEvent,
    WriterPendingEvent,
)

# Educational Profile schema (CORE 1 #2.5 — ported from FEM-modena/graphrag-aixlearning@Angelo)
from .educational_profile import (
    CLASS_FEATURE_LABELS,
    DISABILITY_LABELS,
    FORNITURE_MOBILITY_LABELS,
    GRADE_LABELS,
    OWN_DEVICE_LABELS,
    STUDENT_ATTR_LABELS,
    ClassFeature,
    ClassroomEnvironment,
    DisabilityType,
    EducationalGroup,
    EducationalProfile,
    FornitureMobility,
    GradeLevel,
    OwnDevicePolicy,
    StudentAttribute,
)
from .models import (
    ConceptGraph,
    ConceptGraphEdge,
    ConceptGraphNode,
    ConfidenceLevel,
    ContextData,
    ContextRequest,
    ContextResponse,
    DomainPromptContext,
    DomainType,
    ExplainabilitySummary,
    # Explainability models
    GraphPath,
    HealthResponse,
    KGStats,
    LanguageType,
    MethodologyExplainability,
    MethodologyInfo,
    MetricsInfo,
    QueryInfo,
    RawNode,
    RetrievalPhase,
    ScoringBreakdown,
)

__all__ = [
    "ContextRequest",
    "ContextResponse",
    "MethodologyInfo",
    "QueryInfo",
    "ContextData",
    "DomainPromptContext",
    "HealthResponse",
    "RawNode",
    "MetricsInfo",
    "ConfidenceLevel",
    "DomainType",
    "LanguageType",
    "GraphPath",
    "ScoringBreakdown",
    "MethodologyExplainability",
    "RetrievalPhase",
    "KGStats",
    "ExplainabilitySummary",
    "ConceptGraphNode",
    "ConceptGraphEdge",
    "ConceptGraph",
    # Educational Profile (#2.5)
    "GradeLevel",
    "DisabilityType",
    "ClassFeature",
    "StudentAttribute",
    "FornitureMobility",
    "OwnDevicePolicy",
    "EducationalGroup",
    "ClassroomEnvironment",
    "EducationalProfile",
    "GRADE_LABELS",
    "DISABILITY_LABELS",
    "CLASS_FEATURE_LABELS",
    "STUDENT_ATTR_LABELS",
    "FORNITURE_MOBILITY_LABELS",
    "OWN_DEVICE_LABELS",
    # Public Agent API (#7)
    "AgentRunRequest",
    "AgentRunResponse",
    "AgentRunMeta",
    "CriticScores",
    "MediaCounts",
    "PlannerInfo",
    "RetrieverInfo",
    "AgentStreamEvent",
    "PlannerEvent",
    "RetrieverEvent",
    "WriterPendingEvent",
    "WriterEvent",
    "CriticEvent",
    "DoneEvent",
    "ErrorEvent",
]
